version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: latexmk LNI-test-en
       - store_artifacts:
          path: LNI-test-en.pdf
       - run: latexmk LNI-test-de
       - store_artifacts:
          path: LNI-test-de.pdf
