name: check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    name: CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: Lint CHANGELOG.md
        uses: jbangdev/jbang-action@v0.115.0
        with:
          script: com.github.nbbrd.heylogs:heylogs-cli:0.7.2:bin
          scriptargs: "check CHANGELOG.md"

  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          package_file: Texlivefile

  build:
    runs-on: ubuntu-latest
    needs: [cache]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        file: ['basic-test-en', 'basic-test-de', 'mwe-en', 'mwe-de']
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: Texlivefile

      - run: updmap -sys

      - run: pdflatex ${{ matrix.file }}
      - run: biber ${{ matrix.file }}
      - run: pdflatex ${{ matrix.file }}
      - run: pdflatex ${{ matrix.file }}
      - run: texlogsieve ${{ matrix.file }}.log

      - name: Upload PDF and log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: |
            *.pdf
            *.log

  ctan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: Prepare for CTAN
        run: |
          git config --global --add safe.directory /__w/biblatex-lni/biblatex-lni
          ./release.sh
      - name: Upload CTAN build
        uses: actions/upload-artifact@v4
        with:
          name: CTAN
          path: 'biblatex-lni.zip'
      - name: pkgcheck
        run: |
            set -e
            wget https://gitlab.com/Lotz/pkgcheck/raw/master/bin/pkgcheck -q --output-document=/usr/local/bin/pkgcheck && chmod a+x /usr/local/bin/pkgcheck
            mv biblatex-lni.zip /tmp
            cd /tmp
            unzip biblatex-lni.zip
            pkgcheck -d /tmp/biblatex-lni
  
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
